---
# Synchronize and delete files in dest on the remote host that are not found in src of localhost.
- name: app | code sync
  git:
    repo: "https://github.com/rofrantz/random-photo"
    dest: "{{ project_destination_folder }}"
    force: true

- name: app | install config.ini
  template:
    src:  "app/config.ini"
    dest: "{{ project_destination_folder }}/app/config.ini"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0644

- name: app | composer install
  composer:
    command: "install"
    working_dir: "{{ project_destination_folder }}"

- name: app | bower install
  bower: path="{{ project_destination_folder }}"

- name: app | permissions
  file:
    path: "{{ project_destination_folder }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    recurse: yes
    mode: 0644
