---
- name: php | extensions
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - php7.0-common
    - php7.0-fpm
    - php7.0-cli
    - php7.0-curl
    - php7.0-xml
    - php7.0-mbstring
    - php7.0-zip
